from models import User, Chat, Iteration
from sqlalchemy import text
from functions import get_conn
import streamlit as st


@st.cache_resource
def init_db():
    conn = get_conn()
    with conn.session as session:
        session.execute(
            text("""

    CREATE TABLE IF NOT EXISTS public.user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    email character varying NOT NULL,
    age integer,
    CONSTRAINT user_pkey PRIMARY KEY (id)
    );
                            

    CREATE TABLE IF NOT EXISTS public.chat (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id integer,
    topic character varying NOT NULL,
    timestamp timestamp without time zone NOT NULL,
    CONSTRAINT chat_pkey PRIMARY KEY (id),
    CONSTRAINT chat_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user(id)
    );
                
    CREATE TABLE IF NOT EXISTS public.iteration (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    chat_id integer,
    message character varying NOT NULL,
    response character varying NOT NULL,
    CONSTRAINT iteration_pkey PRIMARY KEY (id),
    CONSTRAINT iteration_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chat(id)
    );
                

    CREATE TABLE IF NOT EXISTS public.deck (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    timestamp timestamp without time zone NOT NULL,
    CONSTRAINT deck_pkey PRIMARY KEY (id),
    CONSTRAINT deck_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user(id)
    );

    CREATE TABLE IF NOT EXISTS public.flashcard (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    deck_id integer NOT NULL,
    image_path_question character varying,
    question character varying NOT NULL,
    image_path_answer character varying,
    answer character varying NOT NULL,
    CONSTRAINT flashcard_pkey PRIMARY KEY (id),
    CONSTRAINT flashcard_deck_id_fkey FOREIGN KEY (deck_id) REFERENCES public.deck(id)
    );


    CREATE TABLE IF NOT EXISTS public.exerciseset (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    timestamp timestamp without time zone NOT NULL,
    CONSTRAINT exerciseset_pkey PRIMARY KEY (id),
    CONSTRAINT exerciseset_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user(id)
    );

    CREATE TABLE IF NOT EXISTS public.exercise (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    exerciseSet_id integer NOT NULL,
    image_path_question character varying,
    question character varying NOT NULL,
    image_path_answer character varying,
    answer character varying NOT NULL,
    CONSTRAINT exercise_pkey PRIMARY KEY (id),
    CONSTRAINT exercise_exerciseSet_id_fkey FOREIGN KEY (exerciseSet_id) REFERENCES public.exerciseset(id)
    );

    """))
        session.commit()